lib.name = pi2c_4encoder
class.sources = pi2c_4encoder.c
common.sources = ../../drivers/src/encoder4.c ../../drivers/src/I2C.c ../../drivers/src/hsv_to_rgb.c
datafiles = pi2c-help.pd
cflags=-I../../drivers/src
include ../Makefile.pdlibbuilder
