lib.name = pi2c_oled
class.sources = pi2c_oled.c
common.sources = ../../drivers/src/oled.c ../../drivers/src/I2C.c vec.c
datafiles = pi2c-help.pd
cflags=-I../../drivers/src -Wno-unused-parameter
include ../Makefile.pdlibbuilder
