lib.name = pi2c_8encoder
class.sources = pi2c_8encoder.c
common.sources = ../../drivers/src/encoder8.c ../../drivers/src/I2C.c
# datafiles = pi2c-help.pd pi2c.pd
cflags=-I../../drivers/src
include ../Makefile.pdlibbuilder
